
module.exports = {
    SLACK_BOT_TOKEN : 'xoxb-210106942755-jl5Kc0pbtXoJdQoNmhQBFP09',
    SLACK_LOG_LEVEL : 'verbose',
    WIT_API_TOKEN : 'ABXYQMYS4TBS7YJSD7SSFAXX6XYLWCWY',
    GOOGLE_GEOCODING_API_KEY : 'AIzaSyCLrBZ9GZqsl49wWSziK-38KXIQta4WX08',
    GOOGLE_TIMEZONE_API_KEY : 'AIzaSyCsJo2aaaIxBfZNewwCD7OvAN2dkwUT2lo'
};